/**
 * Realistic mock workspace for Milestone 1 — a solo builder shipping the
 * Productivity OS MVP. Aligned with the approved visual reference and
 * replaced by real API calls in Milestone 2; shapes match backend contracts.
 *
 * Timestamps are authored relative to "now" at module load so relative
 * times ("2h ago") always read naturally in the browser.
 */
import { mockGoals } from "@/features/goals/mock";
import type { Goal } from "@/features/goals/types";
import { mockProjects } from "@/features/projects/mock";
import type { Project } from "@/features/projects/types";
import { toISODate } from "@/lib/utils/date";

import type { Task } from "./types";

// Projects and goals live in their own features (canonical mocks);
// re-exported here so existing task-side imports keep working.
export { mockGoals, mockProjects };

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 3_600_000).toISOString();
}

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 86_400_000).toISOString();
}

function daysFromNow(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return toISODate(date);
}

export const mockTasks: Task[] = [
  // — Today's Top 3 —
  {
    id: "task-01",
    title: "Finish authentication",
    description:
      "Close out the auth slice: verify refresh-token rotation on /api/v1/auth/refresh, confirm the cookie is scoped to /api/v1/auth, and finish the login rate-limiter tests.",
    status: "IN_PROGRESS",
    priority: "HIGH",
    energy: "HIGH",
    estimatedMinutes: 90,
    dueDate: daysFromNow(0),
    scheduledTime: "09:00",
    recurrence: "Mon, Tue, Wed",
    projectId: "proj-pos",
    completedAt: null,
    createdAt: hoursAgo(52),
    updatedAt: hoursAgo(2),
  },
  {
    id: "task-02",
    title: "Build task dashboard",
    description:
      "First frontend milestone: login screen, three-zone app shell, and the Today dashboard with realistic mock data. Dark-first, calm, no visual noise.",
    status: "PLANNED",
    priority: "HIGH",
    energy: "MEDIUM",
    estimatedMinutes: 120,
    dueDate: daysFromNow(0),
    scheduledTime: "14:00",
    projectId: "proj-pos",
    completedAt: null,
    createdAt: hoursAgo(30),
    updatedAt: hoursAgo(5),
  },
  {
    id: "task-03",
    title: "Review API implementation",
    description:
      "Self-review the daily-plan vertical slice against the spec before invoking the reviewer: capacity rollover, planned-date immutability, error codes.",
    status: "PLANNED",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 45,
    dueDate: daysFromNow(0),
    scheduledTime: "10:30",
    projectId: "proj-pos",
    completedAt: null,
    createdAt: hoursAgo(28),
    updatedAt: hoursAgo(6),
  },

  // — Planned today —
  {
    id: "task-04",
    title: "Fix validation",
    description:
      "Trim whitespace before validating email, disable submit while pending, and surface the 401 invalid_credentials error inline instead of a generic message.",
    status: "PLANNED",
    priority: "HIGH",
    energy: "MEDIUM",
    estimatedMinutes: 45,
    dueDate: daysFromNow(0),
    scheduledTime: "12:00",
    projectId: "proj-pos",
    completedAt: null,
    createdAt: hoursAgo(20),
    updatedAt: hoursAgo(8),
  },
  {
    id: "task-05",
    title: "Write documentation",
    description:
      "Short completion report for the auth + task slice: files changed, acceptance criteria status, deviations, follow-ups.",
    status: "PLANNED",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 90,
    dueDate: daysFromNow(1),
    scheduledTime: "16:00",
    projectId: "proj-pos",
    completedAt: null,
    createdAt: hoursAgo(26),
    updatedAt: hoursAgo(26),
  },
  {
    id: "task-06",
    title: "Review database schema",
    description:
      "Check the Flyway migrations against the domain model: indexes, uniqueness constraints, timestamptz coverage.",
    status: "PLANNED",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 60,
    dueDate: daysFromNow(1),
    scheduledTime: "11:00",
    recurrence: "Mon, Wed, Fri",
    projectId: "proj-pos",
    completedAt: null,
    createdAt: hoursAgo(18),
    updatedAt: hoursAgo(18),
  },
  {
    id: "task-07",
    title: "Update landing page",
    description:
      "Refresh the hero copy and swap in the new Today dashboard screenshot.",
    status: "PLANNED",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 60,
    dueDate: daysFromNow(3),
    scheduledTime: "15:30",
    projectId: "proj-web",
    completedAt: null,
    createdAt: hoursAgo(40),
    updatedAt: hoursAgo(40),
  },
  {
    id: "task-08",
    title: "Prepare for sprint review",
    description:
      "Demo script: login → shell → Today. Note known limitations and milestone 2 scope.",
    status: "PLANNED",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 30,
    dueDate: daysFromNow(4),
    scheduledTime: "09:30",
    projectId: "proj-mobile",
    completedAt: null,
    createdAt: hoursAgo(44),
    updatedAt: hoursAgo(44),
  },

  // — Unplanned (inbox) —
  {
    id: "task-09",
    title: "Check emails",
    description: null,
    status: "INBOX",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 15,
    dueDate: null,
    projectId: "proj-personal",
    completedAt: null,
    createdAt: hoursAgo(9),
    updatedAt: hoursAgo(9),
  },
  {
    id: "task-10",
    title: "Respond to messages",
    description: null,
    status: "INBOX",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 20,
    dueDate: null,
    projectId: "proj-personal",
    completedAt: null,
    createdAt: hoursAgo(7),
    updatedAt: hoursAgo(7),
  },

  // — More captured inbox items —
  {
    id: "task-15",
    title: "Read ADR-004 on auth isolation",
    description: null,
    status: "INBOX",
    priority: "MEDIUM",
    energy: "LOW",
    estimatedMinutes: 20,
    dueDate: null,
    projectId: null,
    completedAt: null,
    createdAt: hoursAgo(9),
    updatedAt: hoursAgo(9),
  },
  {
    id: "task-16",
    title: "Refactor task repository queries",
    description:
      "Extract the user-scoped finders into a single place; the controller review noted duplication between active and deleted listing.",
    status: "INBOX",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 45,
    dueDate: null,
    projectId: null,
    completedAt: null,
    createdAt: hoursAgo(14),
    updatedAt: hoursAgo(14),
  },
  {
    id: "task-17",
    title: "Update OpenAPI annotations",
    description: null,
    status: "INBOX",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 25,
    dueDate: null,
    projectId: null,
    completedAt: null,
    createdAt: hoursAgo(30),
    updatedAt: hoursAgo(30),
  },
  {
    id: "task-18",
    title: "Plan next sprint scope",
    description:
      "Draft the milestone 2 slice list: inbox triage, task lifecycle actions, and connecting the real login endpoint.",
    status: "INBOX",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 30,
    dueDate: null,
    projectId: null,
    completedAt: null,
    createdAt: hoursAgo(46),
    updatedAt: hoursAgo(46),
  },
  {
    id: "task-19",
    title: "Buy new monitor",
    description: null,
    status: "INBOX",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 15,
    dueDate: null,
    projectId: "proj-personal",
    completedAt: null,
    createdAt: hoursAgo(50),
    updatedAt: hoursAgo(50),
  },

  // — Project history (completed work that gives projects real progress) —
  {
    id: "task-20",
    title: "Set up Spring Boot project skeleton",
    description: null,
    status: "COMPLETED",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 60,
    dueDate: null,
    projectId: "proj-pos",
    completedAt: daysAgo(21),
    createdAt: daysAgo(22),
    updatedAt: daysAgo(21),
  },
  {
    id: "task-21",
    title: "Design tasks table migration",
    description: null,
    status: "COMPLETED",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 45,
    dueDate: null,
    projectId: "proj-pos",
    completedAt: daysAgo(18),
    createdAt: daysAgo(19),
    updatedAt: daysAgo(18),
  },
  {
    id: "task-22",
    title: "Implement task lifecycle endpoints",
    description: null,
    status: "COMPLETED",
    priority: "HIGH",
    energy: "HIGH",
    estimatedMinutes: 120,
    dueDate: null,
    projectId: "proj-pos",
    completedAt: daysAgo(14),
    createdAt: daysAgo(16),
    updatedAt: daysAgo(14),
  },
  {
    id: "task-23",
    title: "Write daily top 3 specification",
    description: null,
    status: "COMPLETED",
    priority: "MEDIUM",
    energy: "LOW",
    estimatedMinutes: 50,
    dueDate: null,
    projectId: "proj-pos",
    completedAt: daysAgo(12),
    createdAt: daysAgo(13),
    updatedAt: daysAgo(12),
  },
  {
    id: "task-24",
    title: "Configure Docker PostgreSQL",
    description: null,
    status: "COMPLETED",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 25,
    dueDate: null,
    projectId: "proj-pos",
    completedAt: daysAgo(9),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(9),
  },
  {
    id: "task-25",
    title: "Add JWT login endpoint",
    description: null,
    status: "COMPLETED",
    priority: "HIGH",
    energy: "HIGH",
    estimatedMinutes: 90,
    dueDate: null,
    projectId: "proj-pos",
    completedAt: daysAgo(6),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(6),
  },
  {
    id: "task-26",
    title: "Audit mobile onboarding flow",
    description: null,
    status: "COMPLETED",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 55,
    dueDate: null,
    projectId: "proj-mobile",
    completedAt: daysAgo(8),
    createdAt: daysAgo(9),
    updatedAt: daysAgo(8),
  },
  {
    id: "task-27",
    title: "Fix push notification deep links",
    description: null,
    status: "COMPLETED",
    priority: "HIGH",
    energy: "MEDIUM",
    estimatedMinutes: 70,
    dueDate: null,
    projectId: "proj-mobile",
    completedAt: daysAgo(5),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
  },
  {
    id: "task-28",
    title: "Improve offline sync resilience",
    description: null,
    status: "COMPLETED",
    priority: "MEDIUM",
    energy: "HIGH",
    estimatedMinutes: 110,
    dueDate: null,
    projectId: "proj-mobile",
    completedAt: daysAgo(3),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(3),
  },
  {
    id: "task-29",
    title: "Consolidate marketing page copy",
    description: null,
    status: "COMPLETED",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 40,
    dueDate: null,
    projectId: "proj-web",
    completedAt: daysAgo(7),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
  },
  {
    id: "task-30",
    title: "Migrate images to AVIF",
    description: null,
    status: "COMPLETED",
    priority: "LOW",
    energy: "MEDIUM",
    estimatedMinutes: 35,
    dueDate: null,
    projectId: "proj-web",
    completedAt: daysAgo(4),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  },
  {
    id: "task-31",
    title: "Renew passport",
    description: null,
    status: "COMPLETED",
    priority: "MEDIUM",
    energy: "LOW",
    estimatedMinutes: 30,
    dueDate: null,
    projectId: "proj-personal",
    completedAt: daysAgo(11),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(11),
  },
  {
    id: "task-32",
    title: "Quarterly tax paperwork",
    description: null,
    status: "COMPLETED",
    priority: "HIGH",
    energy: "MEDIUM",
    estimatedMinutes: 75,
    dueDate: null,
    projectId: "proj-personal",
    completedAt: daysAgo(6),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(6),
  },
  {
    id: "task-33",
    title: "Install NAS drives and RAID",
    description: null,
    status: "COMPLETED",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 90,
    dueDate: null,
    projectId: "proj-home",
    completedAt: daysAgo(20),
    createdAt: daysAgo(24),
    updatedAt: daysAgo(20),
  },
  {
    id: "task-34",
    title: "Configure automated backups",
    description: null,
    status: "COMPLETED",
    priority: "HIGH",
    energy: "MEDIUM",
    estimatedMinutes: 60,
    dueDate: null,
    projectId: "proj-home",
    completedAt: daysAgo(15),
    createdAt: daysAgo(17),
    updatedAt: daysAgo(15),
  },
  {
    id: "task-35",
    title: "Set up media streaming",
    description: null,
    status: "COMPLETED",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 45,
    dueDate: null,
    projectId: "proj-home",
    completedAt: daysAgo(12),
    createdAt: daysAgo(13),
    updatedAt: daysAgo(12),
  },
  {
    id: "task-36",
    title: "Design portfolio v1",
    description: null,
    status: "COMPLETED",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 180,
    dueDate: null,
    projectId: "proj-portfolio",
    completedAt: daysAgo(100),
    createdAt: daysAgo(105),
    updatedAt: daysAgo(100),
  },
  {
    id: "task-37",
    title: "Deploy portfolio to Vercel",
    description: null,
    status: "COMPLETED",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 30,
    dueDate: null,
    projectId: "proj-portfolio",
    completedAt: daysAgo(95),
    createdAt: daysAgo(97),
    updatedAt: daysAgo(95),
  },
  {
    id: "task-38",
    title: "Add blog to portfolio",
    description: null,
    status: "CANCELLED",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 240,
    dueDate: null,
    projectId: "proj-portfolio",
    completedAt: null,
    createdAt: daysAgo(94),
    updatedAt: daysAgo(90),
  },

  // — Goal-linked project work (research, health, blog archive) —
  {
    id: "task-39",
    title: "Synthesize user interview notes",
    description: null,
    status: "INBOX",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 40,
    dueDate: null,
    projectId: "proj-research",
    completedAt: null,
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(12),
  },
  {
    id: "task-40",
    title: "Draft interview script",
    description: null,
    status: "COMPLETED",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 45,
    dueDate: null,
    projectId: "proj-research",
    completedAt: daysAgo(5),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
  },
  {
    id: "task-41",
    title: "Book three gym sessions",
    description: null,
    status: "INBOX",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 10,
    dueDate: null,
    projectId: "proj-fitness",
    completedAt: null,
    createdAt: hoursAgo(20),
    updatedAt: hoursAgo(20),
  },
  {
    id: "task-42",
    title: "Buy adjustable dumbbells",
    description: null,
    status: "COMPLETED",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 25,
    dueDate: null,
    projectId: "proj-fitness",
    completedAt: daysAgo(10),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(10),
  },
  {
    id: "task-43",
    title: "Two weeks of consistent workouts",
    description: null,
    status: "COMPLETED",
    priority: "MEDIUM",
    energy: "HIGH",
    estimatedMinutes: 60,
    dueDate: null,
    projectId: "proj-fitness",
    completedAt: daysAgo(4),
    createdAt: daysAgo(18),
    updatedAt: daysAgo(4),
  },
  {
    id: "task-44",
    title: "Set screens-off alarm for 22:30",
    description: null,
    status: "INBOX",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 5,
    dueDate: null,
    projectId: "proj-sleep",
    completedAt: null,
    createdAt: hoursAgo(30),
    updatedAt: hoursAgo(30),
  },
  {
    id: "task-45",
    title: "Track sleep for one week",
    description: null,
    status: "COMPLETED",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 15,
    dueDate: null,
    projectId: "proj-sleep",
    completedAt: daysAgo(8),
    createdAt: daysAgo(15),
    updatedAt: daysAgo(8),
  },
  {
    id: "task-46",
    title: "Migrate blog posts to Markdown",
    description: null,
    status: "COMPLETED",
    priority: "LOW",
    energy: "MEDIUM",
    estimatedMinutes: 90,
    dueDate: null,
    projectId: "proj-blog",
    completedAt: daysAgo(100),
    createdAt: daysAgo(102),
    updatedAt: daysAgo(100),
  },

  // — Recently completed —
  {
    id: "task-11",
    title: "Set up database",
    description: null,
    status: "COMPLETED",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 40,
    dueDate: daysFromNow(0),
    projectId: "proj-pos",
    completedAt: hoursAgo(2),
    createdAt: hoursAgo(50),
    updatedAt: hoursAgo(2),
  },
  {
    id: "task-12",
    title: "Configure Vite dev proxy",
    description: null,
    status: "COMPLETED",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 15,
    dueDate: null,
    projectId: "proj-pos",
    completedAt: hoursAgo(5),
    createdAt: hoursAgo(27),
    updatedAt: hoursAgo(5),
  },
  {
    id: "task-13",
    title: "Triage inbox to zero",
    description: null,
    status: "COMPLETED",
    priority: "LOW",
    energy: "LOW",
    estimatedMinutes: 20,
    dueDate: null,
    projectId: null,
    completedAt: hoursAgo(21),
    createdAt: hoursAgo(48),
    updatedAt: hoursAgo(21),
  },
  {
    id: "task-14",
    title: "Review daily plan slice diff",
    description: null,
    status: "COMPLETED",
    priority: "MEDIUM",
    energy: "MEDIUM",
    estimatedMinutes: 40,
    dueDate: null,
    projectId: "proj-pos",
    completedAt: hoursAgo(27),
    createdAt: hoursAgo(52),
    updatedAt: hoursAgo(27),
  },
];

export function findTaskById(id: string): Task | undefined {
  return mockTasks.find((task) => task.id === id);
}

export function findProjectById(id: string | null): Project | undefined {
  return mockProjects.find((project) => project.id === id);
}

export function findGoalById(id: string | null): Goal | undefined {
  return mockGoals.find((goal) => goal.id === id);
}

/** Goal a task rolls up to, via its project. */
export function goalForTask(task: Task): Goal | undefined {
  const project = findProjectById(task.projectId);
  return findGoalById(project?.goalId ?? null);
}
